spring:
  cloud:
    vault:
      # [Vault] token
      token: vault-plaintext-root-token
    config:
      server:
        vault:
        composite:
          - type: vault
            # [Vault] Key Value version 2
            kv-version: 2
            order: 1
          - type: git
            # [Git] Use your fork
            uri: https://github.com/dubaishoaib/config-server-properties
            order: 2
  profiles:
    # [Vault & git]
    active: composite

# [Config server] default port
server.port: 8888

# [Config server] For Encryption
encrypt.key: "Secret Key"